### ISSUE TITLE
Music that downloaded before need to download again and have FileExistsError

### ISSUE THREAD

**Issue by wongcheehong** [xuancong84/pikaraoke#2]
I have added and downloaded the song before. When I search the song again it will force to download again. Maybe check first if the file exist before downloading.
![image](https://user-images.githubusercontent.com/11075969/157450874-2941c6fa-9986-4d4b-bbc8-b88c1ef37931.png)

**Comment by xuancong84** [comment]
Commit b9ddf761c61554e4ddfa64fea6eaf1ab0e6c1595 fixed it.
