### ISSUE TITLE
vocal_splitter stop working after pressing restart

### ISSUE THREAD

**Issue by wongcheehong** [xuancong84/pikaraoke#3]
![image](https://user-images.githubusercontent.com/11075969/157690632-d5ff7ba7-3be3-448f-ae0e-84f6e9376baf.png)
Once I press the restart button, error occurred as shown below:
![image](https://user-images.githubusercontent.com/11075969/157690377-9e468f69-4fc9-428f-b8e6-d0ea47e37fd2.png)

**Comment by xuancong84** [comment]
Commit 7cd9376063803aa77c7140f51837cc1974fbeb3d should have fixed it
