### ISSUE TITLE
Request for new feature: songs categorization

### ISSUE THREAD

**Issue by v1das** [xuancong84/pikaraoke#8]
Hi,

First of all, thank you for this improved version, it has great new features, I really like it.

Question: I mainly use it on Raspberry Pi, so I guess there is no way to have Vocal splitter on RPI4?

Now, suggestion for improvement: It would be grat to have the ability to categorize/assign karaoke songs to different languages and/or genres.

Eg, when searching for song and found the one you like, before downloading song - you could be able to assign it to certain language / category /genre. And then on the Browse page there would be filters to select specific language / category / genre and filter out only those songs.

This could be implemented either by adding some code to the song name (eg "--EN-- for english song) or moving the song to subfolder (eg to "EN" subfolder for english song).

Please consider this in the next version - this would be a great improvement from my view :)

**Comment by xuancong84** [comment]
In general, there are infinite number of ways to categorize songs and different people have different preferences. Implementing those will make the code very complicated and does not have much gains. So the best way is to NOT to do it, making the project succinct. Moreover, this project is NOT designed to keep millions of songs in your reserve, like commercial Karaoke system. You will never need to sing more than 1000 songs at a time right. Just downloading your favorite songs from the web and keeping them is good enough.
